steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/devops-image:v0.1', '.']

images:
  - 'gcr.io/$PROJECT_ID/devops-image:v0.1'

options:
  logging: CLOUD_LOGGING_ONLY
